name: Build

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-22.04

        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v4

            -   name: Set up Python
                uses: actions/setup-python@v5
                with:
                    python-version: 3.9

            -   name: Install Dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            -   name: Build with PyInstaller for Linux
                shell: bash
                run: |
                    pyinstaller --clean --onefile --name flameshot-uploader main.py

            -   name: Upload Artifact
                uses: actions/upload-artifact@v2
                with:
                    name: flameshot-uploader
                    path: dist/